################################################################################
# Copyright (c) 2022 ContinualAI.                                              #
# Copyrights licensed under the MIT License.                                   #
# See the accompanying LICENSE file for terms.                                 #
#                                                                              #
# Date: 02-03-2022                                                             #
# Author(s): Gabriele Graffieti, Lorenzo Pellegrini                            #
# E-mail: contact@continualai.org                                              #
# Website: avalanche.continualai.org                                           #
################################################################################

name: clvision22-challenge
channels:
- conda-forge
- pytorch
dependencies:
- pip
- psutil
- conda-forge::gputil
- wandb
- tensorboard>=1.15
- scikit-learn
- matplotlib
- numpy
- conda-forge::quadprog
- tqdm
- conda-forge::pycocotools
- conda-forge::torchmetrics
- python=3.9
- pytorch::pytorch>=1.8
- pytorch::torchvision
- pytorch::torchaudio
- pip:
    - pytorchcv
    - gdown
    - ctrl-benchmark
    - gym
    - higher
    - lvis